### ISSUE TITLE
Flag intersections by built up area

### ISSUE THREAD

**Issue by ronnyhdez** [ronnyhdez/reclaimed_sites_ab#61]

**Comment by ronnyhdez** [comment]
When reducing from raster to vector, this is the result:

![image](https://github.com/ronnyhdez/reclaimed_sites_ab/assets/24282285/54dee46f-4089-4d1d-934d-63ca8120b1a4)

**Comment by ronnyhdez** [comment]
Ref #70

**Comment by rfernand387** [comment]
I would buffer 30m anyways for any developed area first.  I would then dissolve the polygons after you do that.  It will be smoother on the edges since the buffers are curved.
