### ISSUE TITLE
Which categories should we use for waterbodies?

### ISSUE THREAD

**Issue by ronnyhdez** [ronnyhdez/reclaimed_sites_ab#64]
In the LCC layer, there are the following categories:

1 = water
3 = wetland - treed
7 = wetland

@rfernand387 should we use just water or all of them?

Check ref #56

**Comment by rfernand387** [comment]
Get rid of water.  Keep wetland and wetland treed.

**Comment by ronnyhdez** [comment]
Ref #74 where I'm trying to solve the problem with getting the wetlands categories as vectors to create the buffers

**Comment by ronnyhdez** [comment]
wetlands will be not used for filtering according to meeting in may 30
