### ISSUE TITLE
Filter out disturbed polygons

### ISSUE THREAD

**Issue by ronnyhdez** [ronnyhdez/reclaimed_sites_ab#71]
According to ref #6

**Comment by rfernand387** [comment]
We need to set this protocol down.  The disturbance to consider would be flooding, fire or development.  

Development - any polygons with pixels within 30m of a built up area in any land cover are filtered.
Water - make a worst case water mask using ABMI,NRCan land cover and any polygons with pixels within 30m of this should be filtered

I would make a second filtered site with burnt areas removed (but keep the one with all valid areas as well)
Fire - use thr CFS fire database together with any ABMI/Alberta layers - filter out burnt areas after the abandoned date.

**Comment by ronnyhdez** [comment]
Using all the filter (dates and intersections) we have a total of *61885*.

When filtering by polygons that weren't disturbed, we end up with *49872*

This is without including polygons that can be included if I fix the issue #112
