### ISSUE TITLE
Filter out polygons with well infraestructure

### ISSUE THREAD

**Issue by ronnyhdez** [ronnyhdez/reclaimed_sites_ab#72]
According to ref #6 

This is different from built-up areas, where some polygons can be in places where there is a new development and no longer in the reclamation process. This can be abandoned wells with infrastructure used before getting into the reclamation process.

**Comment by rfernand387** [comment]
I feel you should use the builup layer info only since it will take too long unded onctract to di this visually.  We can sample more polygons than needed and I can filter these visually outside the contract.

**Comment by ronnyhdez** [comment]
This is already done with built-up layer flagging
