### ISSUE TITLE
Reference polygons are also needed!

### ISSUE THREAD

**Issue by rfernand387** [ronnyhdez/reclaimed_sites_ab#90]
Hi.  In our discussions we did not consider reference polygons surrounding the selected ones.  This should be done before hand since it will also help to reduce valid polygons.  Based on https://ftp-public.abmi.ca/home/publications/documents/354_ABMI_2014-05-26_ERMForestedLandsProtocols_AITF_ABMI.pdf the reference plots should be >35m from edge of well site.  We will use 60m to be safe.  In this case,

1.  Create a buffer polygon >60m and <200m from the original reclamation polygon and set an attribute corresponding to the reclamation polygon area. This will be the reference polygon.
2. Clip the reference polygon with the same clip layers you use for reclamation.
3. Summarize the 2020 abmi land cover area by class and the disturbed area for the polygon.
4. Summarize the 2020 abmi land cover using simplified classes for later use: forest, wetland/marsh/fen/swamp,crop/herbacious,other

**Comment by ronnyhdez** [comment]
There is no ABMI layer recent enough to be used. Instead, we can use AER land use asset. When plotting the asset and exploring how the  reference buffer looks like it shows:

![image](https://github.com/user-attachments/assets/4ee86124-3793-41d0-8e83-0d93c8263246)

**Comment by ronnyhdez** [comment]
This is the asset:

```
var aer = ee.Image('projects/ee-eoagsaer/assets/LULC_2022_EE');
```

**Comment by ronnyhdez** [comment]
Ref #130
