### ISSUE TITLE
Attach ABMI land cover to reclamation polygons

### ISSUE THREAD

**Issue by rfernand387** [ronnyhdez/reclaimed_sites_ab#91]
We will use land cover within polygons to filter and also interpret them.

1. Summarize the 2020 abmi land cover area by class and the disturbed area for the polygon.
2. Summarize the 2020 abmi land cover using simplified classes for later use: forest, wetland/marsh/fen/swamp,crop/herbacious,other

**Comment by ronnyhdez** [comment]
There is no publicly available ABMI 2020. We are going to use the AER land cover with the same simplified classes.
