### ISSUE TITLE
Filtering criteria: land cover match between reclamation and reference poly.

### ISSUE THREAD

**Issue by rfernand387** [ronnyhdez/reclaimed_sites_ab#92]
In addition to a minimum area we will also filter to select polygons whose reference polygon matches in current land cover to ensure we actually have similar reference.

Filter criteria for keeping reclamation polygon in sample.  This only requires filter on attributes.

1.  Simplfy ABMI land cover to:
               Forest
               Wetland/Marsh/Swamp
               Crop/herbacious
               Other
2. Set a flag for each land cover type having >25% area of reclamation polygon.
3. Retain reclamation polygon if reference polygon has >5ha of land cover for each flagged land cover.

**Comment by ronnyhdez** [comment]
Ref #130
